version: '3.8'

services:
  funda-assignment-api:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://*:5000                 